### ISSUE TITLE
Mapping Order Status

### ISSUE THREAD

**Issue by hpwebdesign** [Midtrans/Midtrans-Opencart3#13]
If default order statuses in store were changed, so the hardcoded order_status_id in snap.php

`catalog/controller/extension/payment/snap.php`

wouldn't valid anymore.

- Mapping order status in snap seting page to map order status to be changed after transaction.
- Order Status to be mapped:
1. Pending (order_status_id = 1)
2. Processing (order_status_id = 2)
3. Cancelled (order_status_id = 7)
4. Expired (order_status_id = 14)

**Comment by rizdaprasetya** [comment]
Should be solved by this PR few weeks ago
https://github.com/Midtrans/Midtrans-Opencart3/pull/15

Please use the latest version.
Thanks.
