### ISSUE TITLE
Ask...

### ISSUE THREAD

**Issue by mgandha** [Midtrans/Midtrans-Opencart3#18]
Hi team VT, dan pak @harrypujianto 
ask saja. Untuk callback 'payment-notif'
apa makanisme security nya? Karena kan itu meng-ganti status paid di system opencart.
sekilas saya baca tidak x-check ke transaction code ? Betul kah? atau maaf saya mungkin miss sesuatu.

**Comment by rizdaprasetya** [comment]
@Xaxxis / @omarxp silahkan dibantu jawab ya

**Comment by Xaxxis** [comment]
Hi @mgandha Thank you for reaching us. 

Untuk mekanisme securitynya, setiap Midtrans mengirim notifikasi ke URL yang telah diset pada dashboard Midtrans. Otomatis plugins akan cek kembali dengan parameter order-id yang dikirim melalui notifikasi body untuk melakukan API getStatus ke Midtrans. Apakah order yang dikirim oleh notifikasi benar-benar sesuai dengan status transaksi yang ada pada saat itu. Jika valid maka proses akan dilanjutkan mengganti status pada order Opencart

Bisa dilihat pada kode bagian berikut ini, melakukan Handling notifikasi dengan getStatus ke Midtrans API.
https://github.com/Midtrans/Midtrans-Opencart3/blob/master/catalog/controller/extension/payment/snap.php#L439

Terima kasih

**Comment by mgandha** [comment]
Noted @Xaxxis . Tks dan clear.
